Web Proke/Controllers/KatalogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Proke.Models;

namespace Web_Proke.Controllers
{
    public class KatalogController : Controller
    {
        private KutuphaneEntities4 db = new KutuphaneEntities4();

        // GET: Katalog
        public ActionResult Kitaplar()
        {
            var katalog = db.Katalog.Where(x => x.Tür == "Kitap");
            return View(katalog.ToList());
        }

        // GET: Katalog/Details/5
        public ActionResult Ansiklopediler(int? id)
        {
            var katalog = db.Katalog.Where(x => x.Tür == "Ansiklopedi");
            return View(katalog.ToList());
        }

        // GET: Katalog/Create
        public ActionResult Makaleler()
        {
            var katalog = db.Katalog.Where(x => x.Tür == "Makale");
            return View(katalog.ToList());
        }

        // POST: Katalog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KatalogID,Adı,KonuBasliklari,Tür,YayinBilgisi,FizikselNitelik,DolapKodu,AdminID,ISBN_ISSN")] Katalog katalog)
        {
            if (ModelState.IsValid)
            {
                db.Katalog.Add(katalog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AdminID = new SelectList(db.Admin, "AdminID", "KullaniciAdi", katalog.AdminID);
            ViewBag.DolapKodu = new SelectList(db.Konum, "DolapKodu", "Durum", katalog.DolapKodu);
            return View(katalog);
        }

        // GET: Katalog/Edit/5
        public ActionResult Dergiler()
        {
            var katalog = db.Katalog.Where(x => x.Tür == "Dergi");
            return View(katalog.ToList());
        }

        // POST: Katalog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KatalogID,Adı,KonuBasliklari,Tür,YayinBilgisi,FizikselNitelik,DolapKodu,AdminID,ISBN_ISSN")] Katalog katalog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(katalog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AdminID = new SelectList(db.Admin, "AdminID", "KullaniciAdi", katalog.AdminID);
            ViewBag.DolapKodu = new SelectList(db.Konum, "DolapKodu", "Durum", katalog.DolapKodu);
            return View(katalog);
        }

        // GET: Katalog/Delete/5
        public ActionResult DigitalKayitlar(int? id)
        {
            var katalog = db.Katalog.Where(x => x.Tür == "Digital Kayit");
            return View(katalog.ToList());
        }

        // POST: Katalog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Katalog katalog = db.Katalog.Find(id);
            db.Katalog.Remove(katalog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web Proke/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SAÜ-K</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/animate.min.css" rel="stylesheet">
    <link href="~/Content/prettyPhoto.css" rel="stylesheet">
    <link href="~/Content/main.css" rel="stylesheet">
    <link href="~/Content/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/images/ico/apple-touch-icon-57-precomposed.png">

</head>
<body>
    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-4">
                        <div class="top-number"><p><i class="fa fa-phone-square"></i>  (0.264) 295 53 58</p></div>
                    </div>
                    <div class="col-sm-6 col-xs-8">
                        <div class="social">
                            <ul class="social-share">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype"></i></a></li>
                            </ul>
                            <div class="search">
                                <form role="form">
                                    <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                                    <i class="fa fa-search"></i>
                                </form>
                            </div>
                            @Html.Partial("_LoginPartial")
                        </div>
                    </div>
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->
        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>

                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html"><img src="images/logo.png" alt="logo"></a>
                </div>

                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="active">@Html.ActionLink("Ana Sayfa","Index","Home")</li>
                        <li>@Html.ActionLink("Hakkımızda", "About", "Home")</li>
                        <li>@Html.ActionLink("Personel", "Services", "Home")</li>
                        <li>@Html.ActionLink("Fotoğraflar", "Portfilo", "Home")></li>
                        <li>@Html.ActionLink("Çalışma Saatleri", "Blog", "Home")></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kategoriler<i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Kitaplar", "Kitaplar", "Katalog")</li>
                                <li>@Html.ActionLink("Dergiler", "Dergiler", "Katalog")</li>
                                <li>@Html.ActionLink("Ansiklopediler", "Ansiklopediler", "Katalog")</li>
                                <li>@Html.ActionLink("Digital Kayıtlar", "DigitalKayitlar", "Katalog")</li>
                                <li>@Html.ActionLink("Makaleler", "Makaleler", "Katalog")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("İletişim", "Blog", "Home")></li>
                        
                        
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->

    </header><!--/header-->

    
    @RenderBody()

    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Faq</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.prettyPhoto.js"></script>
    <script src="~/Scripts/jquery.isotope.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/wow.min.js"></script>
</body>
</html>